description "Floofy Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env IllUCOIND_BIN="/usr/bin/floofyd"
env IllUCOIND_USER="floofy"
env IllUCOIND_GROUP="floofy"
env IllUCOIND_PIDDIR="/var/run/floofyd"
# upstart can't handle variables constructed with other variables
env IllUCOIND_PIDFILE="/var/run/floofyd/floofyd.pid"
env IllUCOIND_CONFIGFILE="/etc/floofy/floofy.conf"
env IllUCOIND_DATADIR="/var/lib/floofyd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # floofyd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$IllUCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run floofyd."
        echo "The setting must appear in $IllUCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Floofy Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$IllUCOIND_PIDDIR"
    chmod 0755 "$IllUCOIND_PIDDIR"
    chown $IllUCOIND_USER:$IllUCOIND_GROUP "$IllUCOIND_PIDDIR"
    chown $IllUCOIND_USER:$IllUCOIND_GROUP "$IllUCOIND_CONFIGFILE"
    chmod 0660 "$IllUCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$IllUCOIND_PIDFILE" \
    --chuid $IllUCOIND_USER:$IllUCOIND_GROUP \
    --exec "$IllUCOIND_BIN" \
    -- \
    -pid="$IllUCOIND_PIDFILE" \
    -conf="$IllUCOIND_CONFIGFILE" \
    -datadir="$IllUCOIND_DATADIR" \
    -disablewallet \
    -daemon

