#!/bin/bash
#
#  floofyd The floofy core server.
#
#
# chkconfig: 345 80 20
# description: floofyd
# processname: floofyd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/floofyd, see below
if [ -f /etc/sysconfig/floofyd ]; then
        . /etc/sysconfig/floofyd
fi

RETVAL=0

prog=floofyd
# you can override the lockfile via IllUCOIND_LOCKFILE in /etc/sysconfig/floofyd
lockfile=${IllUCOIND_LOCKFILE-/var/lock/subsys/floofyd}

# floofyd defaults to /usr/bin/floofyd, override with IllUCOIND_BIN
floofyd=${IllUCOIND_BIN-/usr/bin/floofyd}

# floofyd opts default to -disablewallet, override with IllUCOIND_OPTS
floofyd_opts=${IllUCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $floofyd $floofyd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
